services:
  cthulhu:
    image: ghcr.io/n0hor/cthulhu:latest
    ports:
      - "8080:8080"
    volumes:
      - ./conf.yml:/app/conf.yml:ro
    depends_on:
      - demo_app

  demo_app:
    build:
      context: ./demo_app
      dockerfile: Dockerfile
    expose:
      - "9000"